# 1.4.5 Morphological Transformations

## 1. Erosion

In [4]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt

In [5]:
resource_path = os.getcwd() + "/resource/"
img = cv2.imread(resource_path + "dog.jpg")
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations = 1)

In [3]:
cv2.imshow('img',img)
cv2.imshow('erosion',erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 2. Dilation

In [6]:
resource_path = os.getcwd() + "/resource/"
img = cv2.imread(resource_path + "dog.jpg")
kernel = np.ones((5,5),np.uint8)
dilation = cv2.dilate(img,kernel,iterations = 1)

In [7]:
cv2.imshow('img',img)
cv2.imshow('erosion',erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 3. Opening

In [9]:
resource_path = os.getcwd() + "/resource/"
img = cv2.imread(resource_path + "dog.jpg")
kernel = np.ones((5,5),np.uint8)
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)

In [10]:
cv2.imshow('img',img)
cv2.imshow('opening',opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 4. Closing

In [12]:
resource_path = os.getcwd() + "/resource/"
img = cv2.imread(resource_path + "dog.jpg")
kernel = np.ones((5,5),np.uint8)
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

In [13]:
cv2.imshow('img',img)
cv2.imshow('opening',opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 5. Morphological Gradient

In [14]:
resource_path = os.getcwd() + "/resource/"
img = cv2.imread(resource_path + "dog.jpg")
kernel = np.ones((5,5),np.uint8)
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)

In [15]:
cv2.imshow('img',img)
cv2.imshow('opening',opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 6. Top Hat

In [16]:
resource_path = os.getcwd() + "/resource/"
img = cv2.imread(resource_path + "dog.jpg")
kernel = np.ones((5,5),np.uint8)
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)

In [17]:
cv2.imshow('img',img)
cv2.imshow('opening',opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 7. Black Hat

In [18]:
resource_path = os.getcwd() + "/resource/"
img = cv2.imread(resource_path + "dog.jpg")
kernel = np.ones((5,5),np.uint8)
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)

In [19]:
cv2.imshow('img',img)
cv2.imshow('opening',opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [21]:
cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

In [23]:
cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)