# 1.4.4 Smoothing Images

## Kernel Convolution

In [15]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt

In [16]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [17]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [18]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [19]:
img

array([[6, 3, 3, 1, 5, 0, 5, 5, 9, 8, 5, 9],
       [8, 8, 2, 3, 9, 0, 2, 5, 8, 8, 0, 1],
       [2, 6, 0, 2, 4, 0, 7, 1, 2, 8, 5, 4],
       [9, 7, 8, 9, 1, 0, 0, 8, 9, 8, 0, 0],
       [1, 8, 2, 1, 1, 6, 3, 9, 1, 5, 5, 5],
       [3, 2, 7, 2, 3, 0, 5, 6, 1, 5, 0, 5],
       [6, 6, 8, 2, 0, 8, 9, 9, 3, 5, 8, 0],
       [9, 7, 1, 3, 7, 5, 1, 2, 4, 9, 5, 6],
       [3, 7, 9, 9, 2, 2, 0, 2, 9, 3, 0, 7],
       [9, 3, 0, 6, 4, 7, 1, 5, 7, 9, 7, 2],
       [8, 3, 7, 1, 7, 0, 0, 7, 4, 1, 9, 0],
       [6, 3, 8, 3, 3, 8, 6, 6, 0, 3, 4, 4]])

In [20]:
h,w=img.shape

In [21]:
print(h,w)

12 12


In [22]:
#[*range(-2,3)]

In [23]:
dst = np.zeros((h,w),np.int)

In [24]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [25]:
img

array([[6, 3, 3, 1, 5, 0, 5, 5, 9, 8, 5, 9],
       [8, 8, 2, 3, 9, 0, 2, 5, 8, 8, 0, 1],
       [2, 6, 0, 2, 4, 0, 7, 1, 2, 8, 5, 4],
       [9, 7, 8, 9, 1, 0, 0, 8, 9, 8, 0, 0],
       [1, 8, 2, 1, 1, 6, 3, 9, 1, 5, 5, 5],
       [3, 2, 7, 2, 3, 0, 5, 6, 1, 5, 0, 5],
       [6, 6, 8, 2, 0, 8, 9, 9, 3, 5, 8, 0],
       [9, 7, 1, 3, 7, 5, 1, 2, 4, 9, 5, 6],
       [3, 7, 9, 9, 2, 2, 0, 2, 9, 3, 0, 7],
       [9, 3, 0, 6, 4, 7, 1, 5, 7, 9, 7, 2],
       [8, 3, 7, 1, 7, 0, 0, 7, 4, 1, 9, 0],
       [6, 3, 8, 3, 3, 8, 6, 6, 0, 3, 4, 4]])

In [26]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  13,  -6,  -2,  24, -11,  -9,   4,   8,   8, -19,   0],
       [  0,   7, -18,  -8,   4, -11,  25, -18, -18,   9,   8,   0],
       [  0,  -3,  14,  24, -10,  -7, -18,  13,  17,  10, -18,   0],
       [  0,  20, -16, -10,  -7,  20,  -8,  18, -20,   1,  10,   0],
       [  0, -16,  14,  -5,   9, -22,   2,   0, -11,   9, -23,   0],
       [  0,   1,  16,  -5, -20,  18,  13,  16,  -7,  -5,  22,   0],
       [  0,   5, -23,  -7,  18,   2, -12,  -8,  -7,  19,  -3,   0],
       [  0,   6,  19,  16, -14,  -6,  -6,  -8,  20, -15, -22,   0],
       [  0,  -7, -25,  10,  -6,  21,  -8,   3,   1,  18,   8,   0],
       [  0,  -9,  16, -19,  20, -22, -14,  13,   1, -21,  24,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [31]:
resource_path = os.getcwd() + "/resource/"

In [32]:
img = cv2.imread(resource_path + "lena.png", 0)

In [33]:
h,w=img.shape

In [34]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [35]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [36]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()