# 1.5.2 Harris Corner Detection

## Harris Corner Detector in OpenCV

In [6]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt

In [7]:
resource_path = os.getcwd() + '/resource/'

In [8]:
filename = resource_path + 'horse.bmp'
img = cv2.imread(filename)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gray = np.float32(gray)
dst = cv2.cornerHarris(gray,2,3,0.04)

In [9]:
#result is dilated for marking the corners, not important
dst = cv2.dilate(dst,None)

In [12]:
# Threshold for an optimal value, it may vary depending on the image.
img[dst>0.001*dst.max()]=[0,0,255]

In [13]:
cv2.imshow('dst',img)
if cv2.waitKey(0) & 0xff == 27:
    cv2.destroyAllWindows()

## with Trackbar

In [15]:
def nothing(x):
    pass

In [16]:
cv2.namedWindow('image')
cv2.createTrackbar('threshold', 'image', 10, 1000, nothing)
while(1):
    k = cv2.waitKey(1) & 0xFF
    if k == 27:
        break
    threshold = cv2.getTrackbarPos('threshold', 'image')
    if(threshold <= 1):
        threshold = 1
    img = cv2.imread(filename)
    img[dst > 1. / threshold * dst.max()] = [0, 0, 255]
    cv2.imshow('image',img)
cv2.destroyAllWindows()

## Corner with SubPixel Accuracy

In [55]:
filename = resource_path + 'horse.bmp'
img = cv2.imread(filename)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [56]:
# find Harris corners
gray = np.float32(gray)
dst = cv2.cornerHarris(gray,2,3,0.04)
dst = cv2.dilate(dst,None)
ret, dst = cv2.threshold(dst,0.01*dst.max(),255,0)
dst = np.uint8(dst)
print(ret, dst.shape)

1861669.76 (768, 1024)


In [57]:
# find centroids
ret, labels, stats, centroids = cv2.connectedComponentsWithStats(dst)

In [58]:
# define the criteria to stop and refine the corners
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.001)
corners = cv2.cornerSubPix(gray,np.float32(centroids),(5,5),(-1,-1),criteria)

In [59]:
# Now draw them
res = np.hstack((centroids,corners))
res = np.int0(res)
print(res)

[[ 511  383  511  383]
 [ 425  113  425  111]
 [ 454  111  451  109]
 [ 466  126  465  125]
 [ 440  128  438  126]
 [ 449  129  449  129]
 [ 434  131  433  133]
 [ 467  138  465  136]
 [ 430  139  428  138]
 [ 440  157  440  155]
 [ 488  159  485  156]
 [1006  158 1005  157]
 [1022  161 1021  161]
 [ 953  164  954  164]
 [ 494  166  490  165]
 [ 414  169  413  169]
 [ 836  172  837  172]
 [ 464  173  463  171]
 [ 418  175  418  175]
 [ 505  178  503  177]
 [ 922  176  920  173]
 [ 417  187  417  187]
 [ 500  187  501  186]
 [ 509  197  507  197]
 [ 418  205  418  205]
 [ 420  213  420  212]
 [ 524  212  522  212]
 [ 438  220  437  218]
 [ 212  217  212  217]
 [ 538  224  538  224]
 [ 461  228  459  227]
 [ 421  234  421  234]
 [ 540  235  541  235]
 [ 438  242  439  244]
 [ 749  241  749  241]
 [ 548  243  544  243]
 [ 424  246  423  246]
 [ 432  249  432  246]
 [ 763  248  762  247]
 [ 281  249  281  249]
 [ 715  250  715  248]
 [ 702  251  703  249]
 [ 744  251  744  250]
 [ 781  251

In [60]:
img[res[:,1],res[:,0]]=[0,0,255]
img[res[:,3],res[:,2]] = [0,255,0]
cv2.imwrite('subpixel5.png',img)

True

In [47]:
cv2.imshow('dst', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [61]:
res[:,-1]

array([383, 111, 109, 125, 126, 129, 133, 136, 138, 155, 156, 157, 161,
       164, 165, 169, 172, 171, 175, 177, 173, 187, 186, 197, 205, 212,
       212, 218, 217, 224, 227, 234, 235, 244, 241, 243, 246, 246, 247,
       249, 248, 249, 250, 247, 256, 264, 266, 272, 293, 312, 325, 324,
       329, 344, 348, 351, 355, 348, 354, 354, 353, 365, 360, 361, 361,
       365, 367, 371, 375, 376, 377, 377, 379, 414, 385, 391, 386, 387,
       392, 395, 400, 402, 405, 401, 406, 402, 410, 407, 412, 414, 414,
       419, 423, 423, 424, 425, 427, 432, 432, 436, 436, 441, 432, 438,
       436, 446, 439, 447, 448, 447, 448, 459, 459, 458, 457, 467, 469,
       469, 474, 475, 479, 480, 486, 492, 493, 501, 502, 501, 504, 510,
       518, 529, 530, 533, 535, 585, 584, 585, 586, 602, 613, 620, 626,
       628, 632, 633, 638, 635, 645, 652, 651, 671, 676, 676, 685, 693,
       693, 702, 701, 700, 703, 709, 709, 715, 762], dtype=int64)

In [62]:
for i in range(res.shape[0]):
    cv2.circle(img,(res[i,0],res[i,1]),2,(0,0,255),-1)
    cv2.circle(img,(res[i,2],res[i,3]),3,(0,255,0),-1)

In [63]:
cv2.imshow('dst', img)
cv2.waitKey(0)
cv2.destroyAllWindows()