In [1]:
import cv2
import numpy as np
import os

In [2]:
resource_path = os.getcwd() + '/resource/'
img = cv2.imread(resource_path + 'dog.jpg',0)
cv2.imshow('image',img)
k = cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
print(img)

[[165 165 165 ...  52  52  52]
 [165 165 165 ...  52  52  52]
 [163 163 163 ...  52  52  52]
 ...
 [ 93  94  96 ... 110 109 109]
 [ 94  95  97 ... 110 109 109]
 [ 95  96  98 ... 110 109 109]]


In [4]:
kernel = np.zeros((3,3),dtype=np.uint8)

In [5]:
img2 = img[:]

In [6]:
print(kernel)
print(img)
img2[0,0] = 0
print(img)
print(img2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[165 165 165 ...  52  52  52]
 [165 165 165 ...  52  52  52]
 [163 163 163 ...  52  52  52]
 ...
 [ 93  94  96 ... 110 109 109]
 [ 94  95  97 ... 110 109 109]
 [ 95  96  98 ... 110 109 109]]
[[  0 165 165 ...  52  52  52]
 [165 165 165 ...  52  52  52]
 [163 163 163 ...  52  52  52]
 ...
 [ 93  94  96 ... 110 109 109]
 [ 94  95  97 ... 110 109 109]
 [ 95  96  98 ... 110 109 109]]
[[  0 165 165 ...  52  52  52]
 [165 165 165 ...  52  52  52]
 [163 163 163 ...  52  52  52]
 ...
 [ 93  94  96 ... 110 109 109]
 [ 94  95  97 ... 110 109 109]
 [ 95  96  98 ... 110 109 109]]


In [7]:
## 중심으로 모든 값을 곱해서 더한게 합성곱이다.

In [8]:
print(img)

[[  0 165 165 ...  52  52  52]
 [165 165 165 ...  52  52  52]
 [163 163 163 ...  52  52  52]
 ...
 [ 93  94  96 ... 110 109 109]
 [ 94  95  97 ... 110 109 109]
 [ 95  96  98 ... 110 109 109]]


In [9]:
w,h = img.shape
kw,kh = kernel.shape

In [10]:
print( kw * kh)

9


In [11]:
kernel = np.zeros((3,3), dtype=np.int8)
for i in range(kw):
    for j in range(kh):
        kernel[i,j] = 1
        
kernel[1,1] = 4

In [12]:
print(kernel)

[[1 1 1]
 [1 4 1]
 [1 1 1]]


In [13]:
for i in range(w-1):
    for j in range(h-1):
        if not(i == 0 or j == 0 or i == w or j == h):
            sum = 0
            for z in range(kw):
                for k in range(kh):
                    sum += img[i-1+z, j-1+k] * kernel[z,k]
            temp = int(sum / (kw * kh))
            if temp >= 255:
                img2[i, j] = 255
            else:
                img2[i, j] = temp

In [14]:
print(img2)

[[  0 165 165 ...  52  52  52]
 [165 201 223 ...  71  71  52]
 [163 228 242 ...  78  76  52]
 ...
 [ 93 136 148 ... 175 166 109]
 [ 94 137 150 ... 174 166 109]
 [ 95  96  98 ... 110 109 109]]


In [16]:
cv2.imshow('image',img)
cv2.imshow('image2',img2)
k = cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
for i in range(2):
    for j in range(2):
        if not(i == 0 or j == 0 or i == w or j == h):
            print(int(img[i-1,j-1] * kernel[0,0] + img[i-1,j] * kernel[0,1] + img[i-1,j+1] * kernel[0,2] +
            img[i,j-1] * kernel[1,0] + img[i,j] * kernel[1,1] + img[i,j+1] * kernel[1,2] +
            img[i+1,j-1] * kernel[2,0] + img[i+1,j] * kernel[2,1] + img[i+1,j+1] * kernel[2,2]))
            print(i,j)


404
1 1


In [17]:
print(img[2,2] * kernel[2,2])

33


In [61]:
inp = np.zeros((5,5),dtype=np.int8)

In [62]:
inp2 = [1, 2, 1, 4, 5, 2, 1, 3, 4, 2, 3, 2, 5, 1, 2, 5, 2, 1, 1, 4, 6, 3, 3, 2, 5]

In [66]:
k = 0

In [63]:
inp3 = np.zeros((5,5),dtype=np.int8)

In [65]:
for i in range(5):
    for j in range(5):
        inp3[i][j] = inp2[k]
        k = k + 1

In [67]:
for i in range(5):
    for j in range(5):
        inp[i][j] = inp2[k]
        k = k + 1

In [68]:
inp

array([[1, 2, 1, 4, 5],
       [2, 1, 3, 4, 2],
       [3, 2, 5, 1, 2],
       [5, 2, 1, 1, 4],
       [6, 3, 3, 2, 5]], dtype=int8)

In [69]:
inp3

array([[1, 2, 1, 4, 5],
       [2, 1, 3, 4, 2],
       [3, 2, 5, 1, 2],
       [5, 2, 1, 1, 4],
       [6, 3, 3, 2, 5]], dtype=int8)

In [70]:
kernel = np.zeros((3,3),dtype=np.int8)

In [71]:
kernel

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [72]:
ab = [0, 1, 0, 1, -4, 1, 0, 1, 0]

In [73]:
k = 0

In [74]:
for i in range(3):
    for j in range(3):
        kernel[i][j] = ab[k]
        k = k + 1

In [75]:
kernel

array([[ 0,  1,  0],
       [ 1, -4,  1],
       [ 0,  1,  0]], dtype=int8)

In [76]:
for i in range(5):
    for j in range(5):
        if(i == 0 or j == 0 or i == 4 or j == 4):
            inp3[i, j] = 0
        else:
            sum = 0
            for z in range(3):
                for k in range(3):
                    sum += inp[i-1+z, j-1+k] * kernel[z,k]
            temp = sum
            if temp >= 255:
                inp3[i, j] = 255
            else:
                inp3[i, j] = temp

In [77]:
inp3

array([[  0,   0,   0,   0,   0],
       [  0,   5,  -1,  -6,   0],
       [  0,   3, -13,   8,   0],
       [  0,   3,   7,   4,   0],
       [  0,   0,   0,   0,   0]], dtype=int8)