In [4]:
import cv2
import numpy as np
import os

In [5]:
resource_path = os.getcwd() + '/resource/'
img = cv2.imread(resource_path + 'dog.jpg',0)
cv2.imshow('image',img)
k = cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
print(img)

[[ 32  34  35 ...  55  54  52]
 [ 33  34  34 ...  52  53  52]
 [ 33  34  33 ...  51  53  54]
 ...
 [113 112 114 ...  91  92  95]
 [111 102 112 ...  96 109 109]
 [113 104 106 ...  90 101 104]]


In [6]:
kernel = np.zeros((3,3),dtype=np.uint8)

In [7]:
img2 = img[:]

In [26]:
print(kernel)
print(img)
img2[0,0] = 0
print(img)
print(img2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 32  34  35 ...  55  54  52]
 [ 33  34  34 ...  52  53  52]
 [ 33  34  33 ...  51  53  54]
 ...
 [113 112 114 ...  91  92  95]
 [111 102 112 ...  96 109 109]
 [113 104 106 ...  90 101 104]]
[[ 32  34  35 ...  55  54  52]
 [ 33  34  34 ...  52  53  52]
 [ 33  34  33 ...  51  53  54]
 ...
 [113 112 114 ...  91  92  95]
 [111 102 112 ...  96 109 109]
 [113 104 106 ...  90 101 104]]
[[  0  34  35 ...  55  54  52]
 [ 33  34  34 ...  52  53  52]
 [ 33  34  33 ...  51  53  54]
 ...
 [113 112 114 ...  91  92  95]
 [111 102 112 ...  96 109 109]
 [113 104 106 ...  90 101 104]]


In [7]:
## 중심으로 모든 값을 곱해서 더한게 합성곱이다.

In [27]:
print(img)

[[ 32  34  35 ...  55  54  52]
 [ 33  34  34 ...  52  53  52]
 [ 33  34  33 ...  51  53  54]
 ...
 [113 112 114 ...  91  92  95]
 [111 102 112 ...  96 109 109]
 [113 104 106 ...  90 101 104]]


In [8]:
w,h = img.shape
kw,kh = kernel.shape

In [9]:
print( kw * kh)

9


In [10]:
kernel = np.zeros((3,3), dtype=np.int8)
for i in range(kw):
    for j in range(kh):
        kernel[i,j] = 1
        
kernel[1,1] = 4

In [31]:
print(kernel)

[[1 1 1]
 [1 4 1]
 [1 1 1]]


In [17]:
for i in range(w-1):
    for j in range(h-1):
        if not(i == 0 or j == 0 or i == w or j == h):
            sum = 0
            for z in range(kw):
                for k in range(kh):
                    sum += img[i-1+z, j-1+k] * kernel[z,k]
            temp = int(sum / (kw * kh))
            if temp >= 255:
                img2[i,j] = 255
            else:
                img2[i, j] = temp

In [18]:
print(img2)

[[165 165 165 ...  52  52  52]
 [165 255 255 ... 255 225  52]
 [163 255 255 ... 255 255  52]
 ...
 [ 93 255 255 ... 255 255 109]
 [ 94 241 255 ... 255 255 109]
 [ 95  96  98 ... 110 109 109]]


In [39]:
cv2.imshow('image',img)
cv2.imshow('image2',img2)
k = cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
for i in range(2):
    for j in range(2):
        if not(i == 0 or j == 0 or i == w or j == h):
            print(int(img[i-1,j-1] * kernel[0,0] + img[i-1,j] * kernel[0,1] + img[i-1,j+1] * kernel[0,2] +
            img[i,j-1] * kernel[1,0] + img[i,j] * kernel[1,1] + img[i,j+1] * kernel[1,2] +
            img[i+1,j-1] * kernel[2,0] + img[i+1,j] * kernel[2,1] + img[i+1,j+1] * kernel[2,2]))
            print(i,j)


404
1 1


In [17]:
print(img[2,2] * kernel[2,2])

33
